services:
  - type: web
    name: gatepass-django
    env: python
    plan: free
    buildCommand: cd Gatepass && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: cd Gatepass && gunicorn hostel_gatepass.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

